sonar.projectKey=MatheeshaDias0926_timetable-service
sonar.organization=matheeshadias0926
sonar.projectName=Timetable Service
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,coverage/**
